In [1]:
#pandas tutorial

In [29]:
import pandas as pd
import numpy as np

In [3]:
dict1={"name":["satyam","shivam","sundram"],
         "marks":[45,76,89],
        "city":["sdnagar","sknagar","sdnagar"]
      }

In [4]:
df=pd.DataFrame(dict1)

In [5]:
df

      name  marks     city
0   satyam     45  sdnagar
1   shivam     76  sknagar
2  sundram     89  sdnagar

In [6]:
df.to_csv("friends.csv")

In [7]:
iris=pd.read_csv("iris.csv")

In [8]:
iris

     sepal_length  sepal_width  petal_length  petal_width      class_type
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
iris.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width      class_type
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [10]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [11]:
 iris.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width      class_type
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [12]:
iris.head(5)

   sepal_length  sepal_width  petal_length  petal_width   class_type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [13]:
df[marks]

NameError: name 'marks' is not defined

In [14]:
df[0]

KeyError: 0

In [15]:
df[marks][0]=90

NameError: name 'marks' is not defined

In [16]:
df["marks"][0]=90

<ipython-input-16-e5b9e8566d94>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["marks"][0]=90

In [17]:
df

      name  marks     city
0   satyam     90  sdnagar
1   shivam     76  sknagar
2  sundram     89  sdnagar

In [18]:
dict1["marks"][0]

45

In [20]:
df["name"][1]="roli"

<ipython-input-20-d52aa3221360>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["name"][1]="roli"

In [21]:
df

      name  marks     city
0   satyam     90  sdnagar
1     roli     76  sknagar
2  sundram     89  sdnagar

In [22]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [23]:
dtype(df)

NameError: name 'dtype' is not defined

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
len(df)

3

In [30]:
ser=pd.Series(np.random.rand(34))

In [31]:
ser

0     0.271879
1     0.725902
2     0.794480
3     0.644115
4     0.301854
5     0.401788
6     0.372247
7     0.375001
8     0.270072
9     0.340940
10    0.215297
11    0.376736
12    0.536004
13    0.796994
14    0.407526
15    0.355922
16    0.006250
17    0.991295
18    0.587050
19    0.835066
20    0.026248
21    0.667242
22    0.660724
23    0.667353
24    0.074689
25    0.179064
26    0.590036
27    0.506433
28    0.051262
29    0.410809
30    0.051752
31    0.703454
32    0.170291
33    0.467558
dtype: float64

In [32]:
type(ser)

pandas.core.series.Series

In [33]:
np.dtype\

SyntaxError: unexpected EOF while parsing (<ipython-input-33-c852542c595c>, line 1)

In [34]:
ser.dtypes

dtype('float64')

In [35]:
df.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [37]:
new_df=pd.DataFrame(np.random.rand(50,5))

In [38]:
new_df

           0         1         2         3         4
0   0.127181  0.047807  0.779937  0.222708  0.435624
1   0.852131  0.948242  0.819527  0.493026  0.287602
2   0.114539  0.976093  0.381626  0.174549  0.519169
3   0.793748  0.118405  0.422303  0.842966  0.623022
4   0.791065  0.011876  0.900275  0.936488  0.941794
5   0.081191  0.162372  0.148840  0.587297  0.002316
6   0.037762  0.036271  0.309810  0.509368  0.671553
7   0.613343  0.174915  0.764061  0.074359  0.814581
8   0.364157  0.856104  0.841830  0.022450  0.756758
9   0.935113  0.295318  0.837651  0.321093  0.976568
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294
12  0.759149  0.910999  0.463852  0.262941  0.965408
13  0.223670  0.501795  0.317866  0.073386  0.393678
14  0.606519  0.661361  0.844176  0.321208  0.386989
15  0.659012  0.962240  0.005299  0.953808  0.371460
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
18  0.522000  0.449735  0.351493  0.633939  0.884726
19  0.934181  0.550278  0.915246  0.192584  0.947991
20  0.178426  0.452581  0.883462  0.904569  0.349511
21  0.783381  0.507497  0.904205  0.257224  0.105991
22  0.293961  0.388463  0.845721  0.944120  0.168676
23  0.556294  0.056039  0.240678  0.594611  0.428139
24  0.773874  0.141613  0.115118  0.818784  0.443260
25  0.578766  0.146525  0.091330  0.051120  0.800921
26  0.578864  0.139004  0.682014  0.985596  0.896394
27  0.290345  0.618530  0.014491  0.131589  0.270494
28  0.475393  0.571036  0.585588  0.882782  0.625360
29  0.588090  0.789034  0.329482  0.885604  0.400447
30  0.765992  0.114804  0.004069  0.356070  0.908318
31  0.345534  0.317764  0.304281  0.093469  0.520007
32  0.370343  0.348048  0.960245  0.154072  0.138082
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
36  0.892802  0.614475  0.165252  0.398937  0.871686
37  0.373198  0.515501  0.511298  0.441228  0.022887
38  0.685960  0.186329  0.422453  0.236651  0.644097
39  0.768013  0.635458  0.556460  0.174976  0.985966
40  0.669378  0.053631  0.338458  0.588195  0.337730
41  0.551785  0.389345  0.148430  0.125815  0.479640
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [40]:
new_df.head()

          0         1         2         3         4
0  0.127181  0.047807  0.779937  0.222708  0.435624
1  0.852131  0.948242  0.819527  0.493026  0.287602
2  0.114539  0.976093  0.381626  0.174549  0.519169
3  0.793748  0.118405  0.422303  0.842966  0.623022
4  0.791065  0.011876  0.900275  0.936488  0.941794

In [42]:
new_df.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [43]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
class_type       object
dtype: object

In [44]:
new_df[0][0]="shivam"

In [46]:
new_df
new_df.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [47]:
new_df.sum(axis=0)

1    22.104261
2    25.891500
3    24.165823
4    26.767760
dtype: float64

In [48]:
  ser=new_df.sum(axis=1)

0     1.486077
1     2.548398
2     2.051436
3     2.006697
4     2.790433
5     0.900825
6     1.527001
7     1.827915
8     2.477142
9     2.430630
10    3.366235
11    2.437346
12    2.603199
13    1.286726
14    2.213734
15    2.292808
16    1.743614
17    1.971954
18    2.319892
19    2.606099
20    2.590124
21    1.774916
22    2.346980
23    1.319466
24    1.518774
25    1.089897
26    2.703009
27    1.035104
28    2.664766
29    2.404567
30    1.383262
31    1.235522
32    1.600448
33    2.130251
34    1.453582
35    2.183356
36    2.050349
37    1.490913
38    1.489531
39    2.352860
40    1.318014
41    1.143230
42    2.748548
43    1.480094
44    1.316387
45    1.531974
46    1.851345
47    2.557535
48    2.841737
49    2.434640
dtype: float64

In [49]:
ser

0     0.271879
1     0.725902
2     0.794480
3     0.644115
4     0.301854
5     0.401788
6     0.372247
7     0.375001
8     0.270072
9     0.340940
10    0.215297
11    0.376736
12    0.536004
13    0.796994
14    0.407526
15    0.355922
16    0.006250
17    0.991295
18    0.587050
19    0.835066
20    0.026248
21    0.667242
22    0.660724
23    0.667353
24    0.074689
25    0.179064
26    0.590036
27    0.506433
28    0.051262
29    0.410809
30    0.051752
31    0.703454
32    0.170291
33    0.467558
dtype: float64

In [50]:
type(ser)

pandas.core.series.Series

In [51]:
ser.sum(axis=0)

14.833333294375244

In [52]:
new_df[0][0]=.23678

<ipython-input-52-f70ec6c95a37>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df[0][0]=.23678

In [53]:
 new_df

           0         1         2         3         4
0    0.23678  0.047807  0.779937  0.222708  0.435624
1   0.852131  0.948242  0.819527  0.493026  0.287602
2   0.114539  0.976093  0.381626  0.174549  0.519169
3   0.793748  0.118405  0.422303  0.842966  0.623022
4   0.791065  0.011876  0.900275  0.936488  0.941794
5   0.081191  0.162372  0.148840  0.587297  0.002316
6   0.037762  0.036271  0.309810  0.509368  0.671553
7   0.613343  0.174915  0.764061  0.074359  0.814581
8   0.364157  0.856104  0.841830  0.022450  0.756758
9   0.935113  0.295318  0.837651  0.321093  0.976568
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294
12  0.759149  0.910999  0.463852  0.262941  0.965408
13   0.22367  0.501795  0.317866  0.073386  0.393678
14  0.606519  0.661361  0.844176  0.321208  0.386989
15  0.659012  0.962240  0.005299  0.953808  0.371460
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
18     0.522  0.449735  0.351493  0.633939  0.884726
19  0.934181  0.550278  0.915246  0.192584  0.947991
20  0.178426  0.452581  0.883462  0.904569  0.349511
21  0.783381  0.507497  0.904205  0.257224  0.105991
22  0.293961  0.388463  0.845721  0.944120  0.168676
23  0.556294  0.056039  0.240678  0.594611  0.428139
24  0.773874  0.141613  0.115118  0.818784  0.443260
25  0.578766  0.146525  0.091330  0.051120  0.800921
26  0.578864  0.139004  0.682014  0.985596  0.896394
27  0.290345  0.618530  0.014491  0.131589  0.270494
28  0.475393  0.571036  0.585588  0.882782  0.625360
29   0.58809  0.789034  0.329482  0.885604  0.400447
30  0.765992  0.114804  0.004069  0.356070  0.908318
31  0.345534  0.317764  0.304281  0.093469  0.520007
32  0.370343  0.348048  0.960245  0.154072  0.138082
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
36  0.892802  0.614475  0.165252  0.398937  0.871686
37  0.373198  0.515501  0.511298  0.441228  0.022887
38   0.68596  0.186329  0.422453  0.236651  0.644097
39  0.768013  0.635458  0.556460  0.174976  0.985966
40  0.669378  0.053631  0.338458  0.588195  0.337730
41  0.551785  0.389345  0.148430  0.125815  0.479640
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [55]:
  arr=new_df.to_numpy()

In [56]:
arr.shape

(50, 5)

In [57]:
arr.size

250

In [58]:
new_df.shape

(50, 5)

In [59]:
new_df.size

250

In [60]:
arr.reshpae(25,10)

AttributeError: 'numpy.ndarray' object has no attribute 'reshpae'

In [61]:
arr.reshape(25,10)

array([[0.23678, 0.04780745206329451, 0.7799372862037125,
        0.22270845484201207, 0.43562379040184485, 0.8521308569042666,
        0.9482417731427085, 0.819527431690999, 0.4930264606918445,
        0.28760213272507973],
       [0.11453895691701044, 0.9760928328959396, 0.3816258884164284,
        0.17454889481378266, 0.5191687525066451, 0.7937481074419342,
        0.11840538252017074, 0.4223029655784475, 0.8429663288158257,
        0.6230219250546533],
       [0.7910649255389641, 0.011876003750359132, 0.9002745313843327,
        0.9364882258939424, 0.9417944109214084, 0.08119057358000814,
        0.16237239711389817, 0.14883984983992138, 0.5872967379890094,
        0.002315596333934855],
       [0.037762372525274146, 0.0362707600959018, 0.3098095256566282,
        0.5093681472022588, 0.6715528127370296, 0.6133430485338262,
        0.17491469987134656, 0.7640606383438584, 0.07435867911861371,
        0.8145808405599736],
       [0.36415723632780617, 0.8561040420801229, 0.8418297741625861,
        0.0224497696341025, 0.7567582945675065, 0.9351126153942134,
        0.29531776148698774, 0.8376513179663994, 0.3210933155435185,
        0.976567561546162],
       [0.5784257186911386, 0.9624705156125634, 0.7306395501975038,
        0.8065005921800749, 0.8666240590031246, 0.662007009439085,
        0.3697031864400282, 0.779933358443274, 0.7004151535415148,
        0.5872941652648414],
       [0.7591494957793259, 0.910998901808283, 0.4638515782839663,
        0.26294068610467214, 0.965408113487505, 0.22366987087883372,
        0.5017953599836591, 0.31786606425199715, 0.0733861983685431,
        0.3936782985345081],
       [0.606519390542187, 0.6613608372479537, 0.8441756194725796,
        0.3212080907545438, 0.3869894952599602, 0.6590123779571707,
        0.9622404645649966, 0.005299490244443872, 0.9538081753298624,
        0.37146035758673857],
       [0.11209819123934017, 0.375506708147588, 0.4825217312508915,
        0.5707094473753841, 0.31487656817363696, 0.13914726142780964,
        0.8607731971733834, 0.17868166610931557, 0.7640562670157052,
        0.1684430215152728],
       [0.5219996590928219, 0.4497350022494583, 0.35149269064639865,
        0.6339388806732895, 0.8847258962565138, 0.9341808515328744,
        0.5502777944936899, 0.9152463276257206, 0.19258413277293374,
        0.9479908898055485],
       [0.1784264963139034, 0.4525812001650179, 0.8834621316379844,
        0.9045690756732715, 0.34951135856968807, 0.7833812638276105,
        0.5074971058943131, 0.9042050763535082, 0.25722372861867837,
        0.105990557358143],
       [0.29396107446405073, 0.3884625653268121, 0.8457207767714413,
        0.9441204540535162, 0.16867624032980966, 0.5562940035340369,
        0.05603942288213659, 0.24067767158312514, 0.5946105444313237,
        0.4281386813917549],
       [0.77387417051537, 0.14161256655771248, 0.11511821675888911,
        0.8187836259065991, 0.4432597661752402, 0.5787658046072319,
        0.1465245083384491, 0.09133012588577794, 0.05112037470555586,
        0.8009214918191925],
       [0.5788639956333902, 0.13900443765220993, 0.6820138675946281,
        0.9855963002929409, 0.896394153679521, 0.29034503983994475,
        0.6185296061697022, 0.014490898612716241, 0.13158892200425543,
        0.2704941687356204],
       [0.47539284221965894, 0.5710356299651531, 0.5855878717784212,
        0.8827824998369107, 0.6253604664310002, 0.5880903388354167,
        0.7890342409710487, 0.3294819675027003, 0.8856038556164743,
        0.400447321412839],
       [0.7659917219784622, 0.11480428157082989, 0.004069492053414003,
        0.356070349095693, 0.9083176760842007, 0.3455344107480772,
        0.3177644312345981, 0.30428130955014077, 0.09346903348872626,
        0.5200068129962475],
       [0.37034320952139743, 0.3480483551158958, 0.9602453129422179,
        0.15407217010470453, 0.13808227524399808, 0.192772442141651,
        0.21082554339849124, 0.7181881400250556, 0.6071370945505804,
        0.5941003269615006],
       [0.15958193728105485, 0.6557917598888419, 0.18734424215405487,
        0.0812995325735999, 0.529146427360892, 0.29784232487786144,
        0.5976927735536404, 0.9107008466090385, 0.1799715622089657,
        0.4949905692193107],
       [0.8928024196891797, 0.6144746804372067, 0.16525181243166132,
        0.39893665498702713, 0.8716855547960622, 0.3731979540599988,
        0.5155008375430801, 0.5112977174651884, 0.44122786175354856,
        0.022886916197397467],
       [0.6859595935187902, 0.18632922208427094, 0.42245314712352533,
        0.2366510265169146, 0.6440974279046068, 0.768012755036214,
        0.6354577592669345, 0.556459944644834, 0.17497632937143492,
        0.9859664246446819],
       [0.6693778651374019, 0.05363082822522136, 0.338457568963219,
        0.5881949365185984, 0.337730396220988, 0.5517848891464675,
        0.3893453743218257, 0.1484295706040928, 0.1258148791855218,
        0.4796400885986831],
       [0.27122569304054167, 0.7342828407381707, 0.858976212886196,
        0.8101837037547993, 0.345105697739584, 0.06897943529404527,
        0.6100081926564147, 0.46307974947371744, 0.1040834155425161,
        0.3029227273049053],
       [0.1512850390904713, 0.1979271603558449, 0.34187329285887946,
        0.38426272725281474, 0.3923242877073738, 0.17632194675278634,
        0.018405786672893498, 0.19113896847534995, 0.5063163342693904,
        0.8161133911830657],
       [0.28858503684648873, 0.2182308669370704, 0.3524012614379679,
        0.8424587055056846, 0.4382540731178344, 0.19261714827123455,
        0.3949558834214446, 0.9895038734990623, 0.5768877414248286,
        0.5961876310425718],
       [0.24035220812672675, 0.34219633279123907, 0.7425675870853569,
        0.8916556656037854, 0.8653173748631223, 0.02557590022758449,
        0.906001507382739, 0.7571239864867682, 0.6923016062994877,
        0.07921298510267583]], dtype=object)

In [71]:
new_df.index=np.linspace(49,0,50)

In [66]:
new_df.shape

(50, 5)

In [67]:
sq=np.arange(50)

AttributeError: module 'numpy' has no attribute 'arrange'

In [72]:
new_df

             0         1         2         3         4
49.0   0.23678  0.047807  0.779937  0.222708  0.435624
48.0  0.852131  0.948242  0.819527  0.493026  0.287602
47.0  0.114539  0.976093  0.381626  0.174549  0.519169
46.0  0.793748  0.118405  0.422303  0.842966  0.623022
45.0  0.791065  0.011876  0.900275  0.936488  0.941794
44.0  0.081191  0.162372  0.148840  0.587297  0.002316
43.0  0.037762  0.036271  0.309810  0.509368  0.671553
42.0  0.613343  0.174915  0.764061  0.074359  0.814581
41.0  0.364157  0.856104  0.841830  0.022450  0.756758
40.0  0.935113  0.295318  0.837651  0.321093  0.976568
39.0  0.578426  0.962471  0.730640  0.806501  0.866624
38.0  0.662007  0.369703  0.779933  0.700415  0.587294
37.0  0.759149  0.910999  0.463852  0.262941  0.965408
36.0   0.22367  0.501795  0.317866  0.073386  0.393678
35.0  0.606519  0.661361  0.844176  0.321208  0.386989
34.0  0.659012  0.962240  0.005299  0.953808  0.371460
33.0  0.112098  0.375507  0.482522  0.570709  0.314877
32.0  0.139147  0.860773  0.178682  0.764056  0.168443
31.0     0.522  0.449735  0.351493  0.633939  0.884726
30.0  0.934181  0.550278  0.915246  0.192584  0.947991
29.0  0.178426  0.452581  0.883462  0.904569  0.349511
28.0  0.783381  0.507497  0.904205  0.257224  0.105991
27.0  0.293961  0.388463  0.845721  0.944120  0.168676
26.0  0.556294  0.056039  0.240678  0.594611  0.428139
25.0  0.773874  0.141613  0.115118  0.818784  0.443260
24.0  0.578766  0.146525  0.091330  0.051120  0.800921
23.0  0.578864  0.139004  0.682014  0.985596  0.896394
22.0  0.290345  0.618530  0.014491  0.131589  0.270494
21.0  0.475393  0.571036  0.585588  0.882782  0.625360
20.0   0.58809  0.789034  0.329482  0.885604  0.400447
19.0  0.765992  0.114804  0.004069  0.356070  0.908318
18.0  0.345534  0.317764  0.304281  0.093469  0.520007
17.0  0.370343  0.348048  0.960245  0.154072  0.138082
16.0  0.192772  0.210826  0.718188  0.607137  0.594100
15.0  0.159582  0.655792  0.187344  0.081300  0.529146
14.0  0.297842  0.597693  0.910701  0.179972  0.494991
13.0  0.892802  0.614475  0.165252  0.398937  0.871686
12.0  0.373198  0.515501  0.511298  0.441228  0.022887
11.0   0.68596  0.186329  0.422453  0.236651  0.644097
10.0  0.768013  0.635458  0.556460  0.174976  0.985966
9.0   0.669378  0.053631  0.338458  0.588195  0.337730
8.0   0.551785  0.389345  0.148430  0.125815  0.479640
7.0   0.271226  0.734283  0.858976  0.810184  0.345106
6.0   0.068979  0.610008  0.463080  0.104083  0.302923
5.0   0.151285  0.197927  0.341873  0.384263  0.392324
4.0   0.176322  0.018406  0.191139  0.506316  0.816113
3.0   0.288585  0.218231  0.352401  0.842459  0.438254
2.0   0.192617  0.394956  0.989504  0.576888  0.596188
1.0   0.240352  0.342196  0.742568  0.891656  0.865317
0.0   0.025576  0.906002  0.757124  0.692302  0.079213

In [75]:
new_df.columns

RangeIndex(start=0, stop=5, step=1)

In [84]:
new_df.columns=["first","second","third","fourth","fifth"]

In [77]:
new_df

             0         1         2         3         4
49.0   0.23678  0.047807  0.779937  0.222708  0.435624
48.0  0.852131  0.948242  0.819527  0.493026  0.287602
47.0  0.114539  0.976093  0.381626  0.174549  0.519169
46.0  0.793748  0.118405  0.422303  0.842966  0.623022
45.0  0.791065  0.011876  0.900275  0.936488  0.941794
44.0  0.081191  0.162372  0.148840  0.587297  0.002316
43.0  0.037762  0.036271  0.309810  0.509368  0.671553
42.0  0.613343  0.174915  0.764061  0.074359  0.814581
41.0  0.364157  0.856104  0.841830  0.022450  0.756758
40.0  0.935113  0.295318  0.837651  0.321093  0.976568
39.0  0.578426  0.962471  0.730640  0.806501  0.866624
38.0  0.662007  0.369703  0.779933  0.700415  0.587294
37.0  0.759149  0.910999  0.463852  0.262941  0.965408
36.0   0.22367  0.501795  0.317866  0.073386  0.393678
35.0  0.606519  0.661361  0.844176  0.321208  0.386989
34.0  0.659012  0.962240  0.005299  0.953808  0.371460
33.0  0.112098  0.375507  0.482522  0.570709  0.314877
32.0  0.139147  0.860773  0.178682  0.764056  0.168443
31.0     0.522  0.449735  0.351493  0.633939  0.884726
30.0  0.934181  0.550278  0.915246  0.192584  0.947991
29.0  0.178426  0.452581  0.883462  0.904569  0.349511
28.0  0.783381  0.507497  0.904205  0.257224  0.105991
27.0  0.293961  0.388463  0.845721  0.944120  0.168676
26.0  0.556294  0.056039  0.240678  0.594611  0.428139
25.0  0.773874  0.141613  0.115118  0.818784  0.443260
24.0  0.578766  0.146525  0.091330  0.051120  0.800921
23.0  0.578864  0.139004  0.682014  0.985596  0.896394
22.0  0.290345  0.618530  0.014491  0.131589  0.270494
21.0  0.475393  0.571036  0.585588  0.882782  0.625360
20.0   0.58809  0.789034  0.329482  0.885604  0.400447
19.0  0.765992  0.114804  0.004069  0.356070  0.908318
18.0  0.345534  0.317764  0.304281  0.093469  0.520007
17.0  0.370343  0.348048  0.960245  0.154072  0.138082
16.0  0.192772  0.210826  0.718188  0.607137  0.594100
15.0  0.159582  0.655792  0.187344  0.081300  0.529146
14.0  0.297842  0.597693  0.910701  0.179972  0.494991
13.0  0.892802  0.614475  0.165252  0.398937  0.871686
12.0  0.373198  0.515501  0.511298  0.441228  0.022887
11.0   0.68596  0.186329  0.422453  0.236651  0.644097
10.0  0.768013  0.635458  0.556460  0.174976  0.985966
9.0   0.669378  0.053631  0.338458  0.588195  0.337730
8.0   0.551785  0.389345  0.148430  0.125815  0.479640
7.0   0.271226  0.734283  0.858976  0.810184  0.345106
6.0   0.068979  0.610008  0.463080  0.104083  0.302923
5.0   0.151285  0.197927  0.341873  0.384263  0.392324
4.0   0.176322  0.018406  0.191139  0.506316  0.816113
3.0   0.288585  0.218231  0.352401  0.842459  0.438254
2.0   0.192617  0.394956  0.989504  0.576888  0.596188
1.0   0.240352  0.342196  0.742568  0.891656  0.865317
0.0   0.025576  0.906002  0.757124  0.692302  0.079213

In [78]:
new_df.T

,49.0,48.0,47.0,46.0,45.0,44.0,43.0,42.0,41.0,40.0,...,9.0,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0,0.0
0,0.23678,0.852131,0.114539,0.793748,0.791065,0.081191,0.037762,0.613343,0.364157,0.935113,...,0.669378,0.551785,0.271226,0.068979,0.151285,0.176322,0.288585,0.192617,0.240352,0.025576
1,0.047807,0.948242,0.976093,0.118405,0.011876,0.162372,0.036271,0.174915,0.856104,0.295318,...,0.053631,0.389345,0.734283,0.610008,0.197927,0.018406,0.218231,0.394956,0.342196,0.906002
2,0.779937,0.819527,0.381626,0.422303,0.900275,0.14884,0.30981,0.764061,0.84183,0.837651,...,0.338458,0.14843,0.858976,0.46308,0.341873,0.191139,0.352401,0.989504,0.742568,0.757124
3,0.222708,0.493026,0.174549,0.842966,0.936488,0.587297,0.509368,0.074359,0.02245,0.321093,...,0.588195,0.125815,0.810184,0.104083,0.384263,0.506316,0.842459,0.576888,0.891656,0.692302
4,0.435624,0.287602,0.519169,0.623022,0.941794,0.002316,0.671553,0.814581,0.756758,0.976568,...,0.33773,0.47964,0.345106,0.302923,0.392324,0.816113,0.438254,0.596188,0.865317,0.079213

In [81]:
new_df.sort_index(axis=1,ascending=False)

             4         3         2         1         0
49.0  0.435624  0.222708  0.779937  0.047807   0.23678
48.0  0.287602  0.493026  0.819527  0.948242  0.852131
47.0  0.519169  0.174549  0.381626  0.976093  0.114539
46.0  0.623022  0.842966  0.422303  0.118405  0.793748
45.0  0.941794  0.936488  0.900275  0.011876  0.791065
44.0  0.002316  0.587297  0.148840  0.162372  0.081191
43.0  0.671553  0.509368  0.309810  0.036271  0.037762
42.0  0.814581  0.074359  0.764061  0.174915  0.613343
41.0  0.756758  0.022450  0.841830  0.856104  0.364157
40.0  0.976568  0.321093  0.837651  0.295318  0.935113
39.0  0.866624  0.806501  0.730640  0.962471  0.578426
38.0  0.587294  0.700415  0.779933  0.369703  0.662007
37.0  0.965408  0.262941  0.463852  0.910999  0.759149
36.0  0.393678  0.073386  0.317866  0.501795   0.22367
35.0  0.386989  0.321208  0.844176  0.661361  0.606519
34.0  0.371460  0.953808  0.005299  0.962240  0.659012
33.0  0.314877  0.570709  0.482522  0.375507  0.112098
32.0  0.168443  0.764056  0.178682  0.860773  0.139147
31.0  0.884726  0.633939  0.351493  0.449735     0.522
30.0  0.947991  0.192584  0.915246  0.550278  0.934181
29.0  0.349511  0.904569  0.883462  0.452581  0.178426
28.0  0.105991  0.257224  0.904205  0.507497  0.783381
27.0  0.168676  0.944120  0.845721  0.388463  0.293961
26.0  0.428139  0.594611  0.240678  0.056039  0.556294
25.0  0.443260  0.818784  0.115118  0.141613  0.773874
24.0  0.800921  0.051120  0.091330  0.146525  0.578766
23.0  0.896394  0.985596  0.682014  0.139004  0.578864
22.0  0.270494  0.131589  0.014491  0.618530  0.290345
21.0  0.625360  0.882782  0.585588  0.571036  0.475393
20.0  0.400447  0.885604  0.329482  0.789034   0.58809
19.0  0.908318  0.356070  0.004069  0.114804  0.765992
18.0  0.520007  0.093469  0.304281  0.317764  0.345534
17.0  0.138082  0.154072  0.960245  0.348048  0.370343
16.0  0.594100  0.607137  0.718188  0.210826  0.192772
15.0  0.529146  0.081300  0.187344  0.655792  0.159582
14.0  0.494991  0.179972  0.910701  0.597693  0.297842
13.0  0.871686  0.398937  0.165252  0.614475  0.892802
12.0  0.022887  0.441228  0.511298  0.515501  0.373198
11.0  0.644097  0.236651  0.422453  0.186329   0.68596
10.0  0.985966  0.174976  0.556460  0.635458  0.768013
9.0   0.337730  0.588195  0.338458  0.053631  0.669378
8.0   0.479640  0.125815  0.148430  0.389345  0.551785
7.0   0.345106  0.810184  0.858976  0.734283  0.271226
6.0   0.302923  0.104083  0.463080  0.610008  0.068979
5.0   0.392324  0.384263  0.341873  0.197927  0.151285
4.0   0.816113  0.506316  0.191139  0.018406  0.176322
3.0   0.438254  0.842459  0.352401  0.218231  0.288585
2.0   0.596188  0.576888  0.989504  0.394956  0.192617
1.0   0.865317  0.891656  0.742568  0.342196  0.240352
0.0   0.079213  0.692302  0.757124  0.906002  0.025576

In [83]:
new_df.columns=np.linspace(4,0,5)

In [85]:
new_df

         first    second     third    fourth     fifth
49.0   0.23678  0.047807  0.779937  0.222708  0.435624
48.0  0.852131  0.948242  0.819527  0.493026  0.287602
47.0  0.114539  0.976093  0.381626  0.174549  0.519169
46.0  0.793748  0.118405  0.422303  0.842966  0.623022
45.0  0.791065  0.011876  0.900275  0.936488  0.941794
44.0  0.081191  0.162372  0.148840  0.587297  0.002316
43.0  0.037762  0.036271  0.309810  0.509368  0.671553
42.0  0.613343  0.174915  0.764061  0.074359  0.814581
41.0  0.364157  0.856104  0.841830  0.022450  0.756758
40.0  0.935113  0.295318  0.837651  0.321093  0.976568
39.0  0.578426  0.962471  0.730640  0.806501  0.866624
38.0  0.662007  0.369703  0.779933  0.700415  0.587294
37.0  0.759149  0.910999  0.463852  0.262941  0.965408
36.0   0.22367  0.501795  0.317866  0.073386  0.393678
35.0  0.606519  0.661361  0.844176  0.321208  0.386989
34.0  0.659012  0.962240  0.005299  0.953808  0.371460
33.0  0.112098  0.375507  0.482522  0.570709  0.314877
32.0  0.139147  0.860773  0.178682  0.764056  0.168443
31.0     0.522  0.449735  0.351493  0.633939  0.884726
30.0  0.934181  0.550278  0.915246  0.192584  0.947991
29.0  0.178426  0.452581  0.883462  0.904569  0.349511
28.0  0.783381  0.507497  0.904205  0.257224  0.105991
27.0  0.293961  0.388463  0.845721  0.944120  0.168676
26.0  0.556294  0.056039  0.240678  0.594611  0.428139
25.0  0.773874  0.141613  0.115118  0.818784  0.443260
24.0  0.578766  0.146525  0.091330  0.051120  0.800921
23.0  0.578864  0.139004  0.682014  0.985596  0.896394
22.0  0.290345  0.618530  0.014491  0.131589  0.270494
21.0  0.475393  0.571036  0.585588  0.882782  0.625360
20.0   0.58809  0.789034  0.329482  0.885604  0.400447
19.0  0.765992  0.114804  0.004069  0.356070  0.908318
18.0  0.345534  0.317764  0.304281  0.093469  0.520007
17.0  0.370343  0.348048  0.960245  0.154072  0.138082
16.0  0.192772  0.210826  0.718188  0.607137  0.594100
15.0  0.159582  0.655792  0.187344  0.081300  0.529146
14.0  0.297842  0.597693  0.910701  0.179972  0.494991
13.0  0.892802  0.614475  0.165252  0.398937  0.871686
12.0  0.373198  0.515501  0.511298  0.441228  0.022887
11.0   0.68596  0.186329  0.422453  0.236651  0.644097
10.0  0.768013  0.635458  0.556460  0.174976  0.985966
9.0   0.669378  0.053631  0.338458  0.588195  0.337730
8.0   0.551785  0.389345  0.148430  0.125815  0.479640
7.0   0.271226  0.734283  0.858976  0.810184  0.345106
6.0   0.068979  0.610008  0.463080  0.104083  0.302923
5.0   0.151285  0.197927  0.341873  0.384263  0.392324
4.0   0.176322  0.018406  0.191139  0.506316  0.816113
3.0   0.288585  0.218231  0.352401  0.842459  0.438254
2.0   0.192617  0.394956  0.989504  0.576888  0.596188
1.0   0.240352  0.342196  0.742568  0.891656  0.865317
0.0   0.025576  0.906002  0.757124  0.692302  0.079213

In [95]:
new_df1=new_df

In [94]:
new_df.index=np.arange(50)

In [98]:
new_df

       first    second     third    fourth     fifth
0    0.23678  0.047807  0.779937  0.222708  0.435624
1   0.852131  0.948242  0.819527  0.493026  0.287602
2   0.114539  0.976093  0.381626  0.174549  0.519169
3   0.793748  0.118405  0.422303  0.842966  0.623022
4   0.791065  0.011876  0.900275  0.936488  0.941794
5   0.081191  0.162372  0.148840  0.587297  0.002316
6   0.037762  0.036271  0.309810  0.509368  0.671553
7   0.613343  0.174915  0.764061  0.074359  0.814581
8   0.364157  0.856104  0.841830  0.022450  0.756758
9   0.935113  0.295318  0.837651  0.321093  0.976568
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294
12  0.759149  0.910999  0.463852  0.262941  0.965408
13   0.22367  0.501795  0.317866  0.073386  0.393678
14  0.606519  0.661361  0.844176  0.321208  0.386989
15  0.659012  0.962240  0.005299  0.953808  0.371460
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
18     0.522  0.449735  0.351493  0.633939  0.884726
19  0.934181  0.550278  0.915246  0.192584  0.947991
20  0.178426  0.452581  0.883462  0.904569  0.349511
21  0.783381  0.507497  0.904205  0.257224  0.105991
22  0.293961  0.388463  0.845721  0.944120  0.168676
23  0.556294  0.056039  0.240678  0.594611  0.428139
24  0.773874  0.141613  0.115118  0.818784  0.443260
25  0.578766  0.146525  0.091330  0.051120  0.800921
26  0.578864  0.139004  0.682014  0.985596  0.896394
27  0.290345  0.618530  0.014491  0.131589  0.270494
28  0.475393  0.571036  0.585588  0.882782  0.625360
29   0.58809  0.789034  0.329482  0.885604  0.400447
30  0.765992  0.114804  0.004069  0.356070  0.908318
31  0.345534  0.317764  0.304281  0.093469  0.520007
32  0.370343  0.348048  0.960245  0.154072  0.138082
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
36  0.892802  0.614475  0.165252  0.398937  0.871686
37  0.373198  0.515501  0.511298  0.441228  0.022887
38   0.68596  0.186329  0.422453  0.236651  0.644097
39  0.768013  0.635458  0.556460  0.174976  0.985966
40  0.669378  0.053631  0.338458  0.588195  0.337730
41  0.551785  0.389345  0.148430  0.125815  0.479640
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [100]:
new_df["first"][0]=.456

<ipython-input-100-27fd5c877747>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["first"][0]=.456

In [102]:
new_df1

       first    second     third    fourth     fifth
0      0.456  0.047807  0.779937  0.222708  0.435624
1   0.852131  0.948242  0.819527  0.493026  0.287602
2   0.114539  0.976093  0.381626  0.174549  0.519169
3   0.793748  0.118405  0.422303  0.842966  0.623022
4   0.791065  0.011876  0.900275  0.936488  0.941794
5   0.081191  0.162372  0.148840  0.587297  0.002316
6   0.037762  0.036271  0.309810  0.509368  0.671553
7   0.613343  0.174915  0.764061  0.074359  0.814581
8   0.364157  0.856104  0.841830  0.022450  0.756758
9   0.935113  0.295318  0.837651  0.321093  0.976568
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294
12  0.759149  0.910999  0.463852  0.262941  0.965408
13   0.22367  0.501795  0.317866  0.073386  0.393678
14  0.606519  0.661361  0.844176  0.321208  0.386989
15  0.659012  0.962240  0.005299  0.953808  0.371460
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
18     0.522  0.449735  0.351493  0.633939  0.884726
19  0.934181  0.550278  0.915246  0.192584  0.947991
20  0.178426  0.452581  0.883462  0.904569  0.349511
21  0.783381  0.507497  0.904205  0.257224  0.105991
22  0.293961  0.388463  0.845721  0.944120  0.168676
23  0.556294  0.056039  0.240678  0.594611  0.428139
24  0.773874  0.141613  0.115118  0.818784  0.443260
25  0.578766  0.146525  0.091330  0.051120  0.800921
26  0.578864  0.139004  0.682014  0.985596  0.896394
27  0.290345  0.618530  0.014491  0.131589  0.270494
28  0.475393  0.571036  0.585588  0.882782  0.625360
29   0.58809  0.789034  0.329482  0.885604  0.400447
30  0.765992  0.114804  0.004069  0.356070  0.908318
31  0.345534  0.317764  0.304281  0.093469  0.520007
32  0.370343  0.348048  0.960245  0.154072  0.138082
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
36  0.892802  0.614475  0.165252  0.398937  0.871686
37  0.373198  0.515501  0.511298  0.441228  0.022887
38   0.68596  0.186329  0.422453  0.236651  0.644097
39  0.768013  0.635458  0.556460  0.174976  0.985966
40  0.669378  0.053631  0.338458  0.588195  0.337730
41  0.551785  0.389345  0.148430  0.125815  0.479640
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [103]:
new_df.loc[0,0]=.89

In [104]:
new_df

       first    second     third    fourth     fifth     0
0      0.456  0.047807  0.779937  0.222708  0.435624  0.89
1   0.852131  0.948242  0.819527  0.493026  0.287602   NaN
2   0.114539  0.976093  0.381626  0.174549  0.519169   NaN
3   0.793748  0.118405  0.422303  0.842966  0.623022   NaN
4   0.791065  0.011876  0.900275  0.936488  0.941794   NaN
5   0.081191  0.162372  0.148840  0.587297  0.002316   NaN
6   0.037762  0.036271  0.309810  0.509368  0.671553   NaN
7   0.613343  0.174915  0.764061  0.074359  0.814581   NaN
8   0.364157  0.856104  0.841830  0.022450  0.756758   NaN
9   0.935113  0.295318  0.837651  0.321093  0.976568   NaN
10  0.578426  0.962471  0.730640  0.806501  0.866624   NaN
11  0.662007  0.369703  0.779933  0.700415  0.587294   NaN
12  0.759149  0.910999  0.463852  0.262941  0.965408   NaN
13   0.22367  0.501795  0.317866  0.073386  0.393678   NaN
14  0.606519  0.661361  0.844176  0.321208  0.386989   NaN
15  0.659012  0.962240  0.005299  0.953808  0.371460   NaN
16  0.112098  0.375507  0.482522  0.570709  0.314877   NaN
17  0.139147  0.860773  0.178682  0.764056  0.168443   NaN
18     0.522  0.449735  0.351493  0.633939  0.884726   NaN
19  0.934181  0.550278  0.915246  0.192584  0.947991   NaN
20  0.178426  0.452581  0.883462  0.904569  0.349511   NaN
21  0.783381  0.507497  0.904205  0.257224  0.105991   NaN
22  0.293961  0.388463  0.845721  0.944120  0.168676   NaN
23  0.556294  0.056039  0.240678  0.594611  0.428139   NaN
24  0.773874  0.141613  0.115118  0.818784  0.443260   NaN
25  0.578766  0.146525  0.091330  0.051120  0.800921   NaN
26  0.578864  0.139004  0.682014  0.985596  0.896394   NaN
27  0.290345  0.618530  0.014491  0.131589  0.270494   NaN
28  0.475393  0.571036  0.585588  0.882782  0.625360   NaN
29   0.58809  0.789034  0.329482  0.885604  0.400447   NaN
30  0.765992  0.114804  0.004069  0.356070  0.908318   NaN
31  0.345534  0.317764  0.304281  0.093469  0.520007   NaN
32  0.370343  0.348048  0.960245  0.154072  0.138082   NaN
33  0.192772  0.210826  0.718188  0.607137  0.594100   NaN
34  0.159582  0.655792  0.187344  0.081300  0.529146   NaN
35  0.297842  0.597693  0.910701  0.179972  0.494991   NaN
36  0.892802  0.614475  0.165252  0.398937  0.871686   NaN
37  0.373198  0.515501  0.511298  0.441228  0.022887   NaN
38   0.68596  0.186329  0.422453  0.236651  0.644097   NaN
39  0.768013  0.635458  0.556460  0.174976  0.985966   NaN
40  0.669378  0.053631  0.338458  0.588195  0.337730   NaN
41  0.551785  0.389345  0.148430  0.125815  0.479640   NaN
42  0.271226  0.734283  0.858976  0.810184  0.345106   NaN
43  0.068979  0.610008  0.463080  0.104083  0.302923   NaN
44  0.151285  0.197927  0.341873  0.384263  0.392324   NaN
45  0.176322  0.018406  0.191139  0.506316  0.816113   NaN
46  0.288585  0.218231  0.352401  0.842459  0.438254   NaN
47  0.192617  0.394956  0.989504  0.576888  0.596188   NaN
48  0.240352  0.342196  0.742568  0.891656  0.865317   NaN
49  0.025576  0.906002  0.757124  0.692302  0.079213   NaN

In [109]:
new_df=new_df.drop([0],axis=1)

In [110]:
new_df.dtypes

first      object
second    float64
third     float64
fourth    float64
fifth     float64
dtype: object

In [115]:
new_df.loc[new_df.index,new_df.columns]

       first    second     third    fourth     fifth
0      0.456  0.047807  0.779937  0.222708  0.435624
1   0.852131  0.948242  0.819527  0.493026  0.287602
2   0.114539  0.976093  0.381626  0.174549  0.519169
3   0.793748  0.118405  0.422303  0.842966  0.623022
4   0.791065  0.011876  0.900275  0.936488  0.941794
5   0.081191  0.162372  0.148840  0.587297  0.002316
6   0.037762  0.036271  0.309810  0.509368  0.671553
7   0.613343  0.174915  0.764061  0.074359  0.814581
8   0.364157  0.856104  0.841830  0.022450  0.756758
9   0.935113  0.295318  0.837651  0.321093  0.976568
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294
12  0.759149  0.910999  0.463852  0.262941  0.965408
13   0.22367  0.501795  0.317866  0.073386  0.393678
14  0.606519  0.661361  0.844176  0.321208  0.386989
15  0.659012  0.962240  0.005299  0.953808  0.371460
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
18     0.522  0.449735  0.351493  0.633939  0.884726
19  0.934181  0.550278  0.915246  0.192584  0.947991
20  0.178426  0.452581  0.883462  0.904569  0.349511
21  0.783381  0.507497  0.904205  0.257224  0.105991
22  0.293961  0.388463  0.845721  0.944120  0.168676
23  0.556294  0.056039  0.240678  0.594611  0.428139
24  0.773874  0.141613  0.115118  0.818784  0.443260
25  0.578766  0.146525  0.091330  0.051120  0.800921
26  0.578864  0.139004  0.682014  0.985596  0.896394
27  0.290345  0.618530  0.014491  0.131589  0.270494
28  0.475393  0.571036  0.585588  0.882782  0.625360
29   0.58809  0.789034  0.329482  0.885604  0.400447
30  0.765992  0.114804  0.004069  0.356070  0.908318
31  0.345534  0.317764  0.304281  0.093469  0.520007
32  0.370343  0.348048  0.960245  0.154072  0.138082
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
36  0.892802  0.614475  0.165252  0.398937  0.871686
37  0.373198  0.515501  0.511298  0.441228  0.022887
38   0.68596  0.186329  0.422453  0.236651  0.644097
39  0.768013  0.635458  0.556460  0.174976  0.985966
40  0.669378  0.053631  0.338458  0.588195  0.337730
41  0.551785  0.389345  0.148430  0.125815  0.479640
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [118]:
new_df.loc[(new_df["first"]<0.3)]

       first    second     third    fourth     fifth
2   0.114539  0.976093  0.381626  0.174549  0.519169
5   0.081191  0.162372  0.148840  0.587297  0.002316
6   0.037762  0.036271  0.309810  0.509368  0.671553
13   0.22367  0.501795  0.317866  0.073386  0.393678
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
20  0.178426  0.452581  0.883462  0.904569  0.349511
22  0.293961  0.388463  0.845721  0.944120  0.168676
27  0.290345  0.618530  0.014491  0.131589  0.270494
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [120]:
new_df["first"]

0        0.456
1     0.852131
2     0.114539
3     0.793748
4     0.791065
5     0.081191
6     0.037762
7     0.613343
8     0.364157
9     0.935113
10    0.578426
11    0.662007
12    0.759149
13     0.22367
14    0.606519
15    0.659012
16    0.112098
17    0.139147
18       0.522
19    0.934181
20    0.178426
21    0.783381
22    0.293961
23    0.556294
24    0.773874
25    0.578766
26    0.578864
27    0.290345
28    0.475393
29     0.58809
30    0.765992
31    0.345534
32    0.370343
33    0.192772
34    0.159582
35    0.297842
36    0.892802
37    0.373198
38     0.68596
39    0.768013
40    0.669378
41    0.551785
42    0.271226
43    0.068979
44    0.151285
45    0.176322
46    0.288585
47    0.192617
48    0.240352
49    0.025576
Name: first, dtype: object

In [122]:
new_df.sum(axis=0)

first     22.820797
second    22.104261
third       25.8915
fourth    24.165823
fifth      26.76776
dtype: object

In [124]:
new_df.loc[np.arange(20),["first","second"]]

       first    second
0      0.456  0.047807
1   0.852131  0.948242
2   0.114539  0.976093
3   0.793748  0.118405
4   0.791065  0.011876
5   0.081191  0.162372
6   0.037762  0.036271
7   0.613343  0.174915
8   0.364157  0.856104
9   0.935113  0.295318
10  0.578426  0.962471
11  0.662007  0.369703
12  0.759149  0.910999
13   0.22367  0.501795
14  0.606519  0.661361
15  0.659012  0.962240
16  0.112098  0.375507
17  0.139147  0.860773
18     0.522  0.449735
19  0.934181  0.550278

In [133]:
new_df.loc[0,"first"]=0.9

In [136]:
new_df.loc[np.arange(10),new_df.columns]=0.7

In [137]:
new_df

       first    second     third    fourth     fifth
0        0.7  0.700000  0.700000  0.700000  0.700000
1        0.7  0.700000  0.700000  0.700000  0.700000
2        0.7  0.700000  0.700000  0.700000  0.700000
3        0.7  0.700000  0.700000  0.700000  0.700000
4        0.7  0.700000  0.700000  0.700000  0.700000
5        0.7  0.700000  0.700000  0.700000  0.700000
6        0.7  0.700000  0.700000  0.700000  0.700000
7        0.7  0.700000  0.700000  0.700000  0.700000
8        0.7  0.700000  0.700000  0.700000  0.700000
9        0.7  0.700000  0.700000  0.700000  0.700000
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294
12  0.759149  0.910999  0.463852  0.262941  0.965408
13   0.22367  0.501795  0.317866  0.073386  0.393678
14  0.606519  0.661361  0.844176  0.321208  0.386989
15  0.659012  0.962240  0.005299  0.953808  0.371460
16  0.112098  0.375507  0.482522  0.570709  0.314877
17  0.139147  0.860773  0.178682  0.764056  0.168443
18     0.522  0.449735  0.351493  0.633939  0.884726
19  0.934181  0.550278  0.915246  0.192584  0.947991
20  0.178426  0.452581  0.883462  0.904569  0.349511
21  0.783381  0.507497  0.904205  0.257224  0.105991
22  0.293961  0.388463  0.845721  0.944120  0.168676
23  0.556294  0.056039  0.240678  0.594611  0.428139
24  0.773874  0.141613  0.115118  0.818784  0.443260
25  0.578766  0.146525  0.091330  0.051120  0.800921
26  0.578864  0.139004  0.682014  0.985596  0.896394
27  0.290345  0.618530  0.014491  0.131589  0.270494
28  0.475393  0.571036  0.585588  0.882782  0.625360
29   0.58809  0.789034  0.329482  0.885604  0.400447
30  0.765992  0.114804  0.004069  0.356070  0.908318
31  0.345534  0.317764  0.304281  0.093469  0.520007
32  0.370343  0.348048  0.960245  0.154072  0.138082
33  0.192772  0.210826  0.718188  0.607137  0.594100
34  0.159582  0.655792  0.187344  0.081300  0.529146
35  0.297842  0.597693  0.910701  0.179972  0.494991
36  0.892802  0.614475  0.165252  0.398937  0.871686
37  0.373198  0.515501  0.511298  0.441228  0.022887
38   0.68596  0.186329  0.422453  0.236651  0.644097
39  0.768013  0.635458  0.556460  0.174976  0.985966
40  0.669378  0.053631  0.338458  0.588195  0.337730
41  0.551785  0.389345  0.148430  0.125815  0.479640
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213

In [139]:
new_df.loc[[10,11]]

       first    second     third    fourth     fifth
10  0.578426  0.962471  0.730640  0.806501  0.866624
11  0.662007  0.369703  0.779933  0.700415  0.587294

In [141]:
list1=new_df.columns

In [142]:
list1

Index(['first', 'second', 'third', 'fourth', 'fifth'], dtype='object')

In [149]:
type(list1)

pandas.core.indexes.base.Index

In [155]:
 new_list=list(list1)

In [156]:
new_list.remove("fifth")

In [161]:
new_df.drop([5,6,7],axis=0, inplace=True)

In [162]:
new_df.append=pd.DataFrame(np.random.rand(50,5))

In [165]:
new_df.tail(8)

       first    second     third    fourth     fifth
42  0.271226  0.734283  0.858976  0.810184  0.345106
43  0.068979  0.610008  0.463080  0.104083  0.302923
44  0.151285  0.197927  0.341873  0.384263  0.392324
45  0.176322  0.018406  0.191139  0.506316  0.816113
46  0.288585  0.218231  0.352401  0.842459  0.438254
47  0.192617  0.394956  0.989504  0.576888  0.596188
48  0.240352  0.342196  0.742568  0.891656  0.865317
49  0.025576  0.906002  0.757124  0.692302  0.079213